apiVersion: 1

datasources:
  - name: QuestDB
    uid: questdb
    type: postgres
    access: proxy
    url: host.docker.internal:18812
    user: admin
    secureJsonData:
      password: quest
    jsonData:
      database: qdb
      sslmode: disable
      postgresVersion: 1200
      timescaledb: false
    isDefault: true
    editable: true
